services:
  - type: web
    name: agro-pluse
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    disks:
      - name: agro-data
        mountPath: /opt/render/project/src/data
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_PATH
        value: /opt/render/project/src/data/users.db
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: Dacosta133@
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: CHANGE_ME
      - key: SMTP_PASS
        value: CHANGE_ME
      - key: FROM_EMAIL
        value: CHANGE_ME
      - key: PAYSTACK_SECRET_KEY
        value: CHANGE_ME
      - key: PAYSTACK_PUBLIC_KEY
        value: CHANGE_ME
